---

- name: Initialize
  hosts: all

  tasks:
    - name: Set up SSH authorized key
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user: debian

    - name: Allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%admin\\s"
        line: "%admin ALL=(ALL:ALL) NOPASSWD: ALL"

    - name: Disallow password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: PasswordAuthentication no

    - name: Clear password for debian user
      command: passwd -d debian

    - name: Reboot
      command: reboot
      async: 1
      poll: 0
      ignore_errors: true
