---

- name: Set up SSH authorized key
  authorized_key:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: pi

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication "
    line: PasswordAuthentication no

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Add /etc/hosts entry for hostname
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^127.0.1.1\\s"
    line: "127.0.1.1	{{ inventory_hostname_short }}.localdomain {{ inventory_hostname_short }}"

- name: Upgrade packages
  apt:
    autoremove: yes
    upgrade: dist
    update_cache: yes
    cache_valid_time: 0

- name: Install Vim
  apt:
    name: vim
