---

- name: Install certbot
  apt:
    name: certbot
  tags:
    - cert

- name: Obtain certificate
  command: "certbot certonly -n --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start' --agree-tos -m '{{ certbot.email }}' -d '{{ webserver.vhost }}'"
  args:
    creates: "/etc/letsencrypt/live/{{ webserver.vhost }}"

- name: Schedule certificate renewal
  cron:
    name: certbot
    minute: 0
    hour: 4
    job: "certbot renew -n"
