---

- name: Install certbot
  apt:
    name: certbot
    default_release: jessie-backports
  tags:
    - cert

- name: Find certificates
  stat:
    path: "/etc/letsencrypt/live/{{ item }}"
  register: cert_stat
  with_items: "{{ webserver.vhosts }}"

- name: Obtain certificate for each vhost
  command: "certbot certonly -n --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start' --agree-tos -m {{ certbot.email }} -d {{ item.item }}"
  when: item.stat is not defined or not item.stat.exists
  with_items: "{{ cert_stat.results }}"

- name: Schedule certificate renewal
  cron:
    name: certbot
    minute: 0
    hour: 4
    job: "certbot renew -n"
