---

- name: Add jessie-backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    update_cache: yes
  tags:
    - cert

- name: Install certbot
  apt:
    name: certbot
    default_release: jessie-backports
  tags:
    - cert

- name: Find certificates
  stat:
    path: "/etc/letsencrypt/live/{{ item }}"
  register: cert_stat
  with_items: "{{ webserver.vhosts }}"

- name: Stop nginx
  service:
    name: nginx
    state: stopped
  when: item.stat is not defined or not item.stat.exists
  with_items: "{{ cert_stat.results }}"

- name: Obtain certificate for each vhost
  command: "certbot certonly -n --agree-tos -m {{ certbot.email }} --standalone -d {{ item.item }}"
  when: item.stat is not defined or not item.stat.exists
  with_items: "{{ cert_stat.results }}"
  notify: Restart nginx

- name: Schedule certificate renewal
  cron:
    name: certbot
    hour: 4
    job: "certbot renew -n && service nginx reload"
