---

- name: Install nginx
  apt:
    name: nginx-light

- name: Stat sites-enabled
  stat:
    path: /etc/nginx/sites-enabled
  register: sites_enabled

- name: Remove the default web root
  file:
    path: /var/www/html
    state: absent
  when: sites_enabled.stat.isdir is defined and sites_enabled.stat.isdir

- name: Remove the default sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: absent
  when: sites_enabled.stat.isdir is defined and sites_enabled.stat.isdir

- name: Sync /etc/nginx/sites-available directory
  synchronize:
    src: etc/nginx/sites-available/
    dest: /etc/nginx/sites-available/
    archive: no
    delete: yes
    recursive: yes
    times: yes
  notify: Restart nginx
  tags:
    - configuration

- name: Copy htpasswd file
  copy:
    src: etc/nginx/home.htpasswd
    dest: /etc/nginx/home.htpasswd
  notify: Restart nginx
  tags:
    - configuration

- name: Copy self.crt file
  copy:
    src: etc/nginx/self.crt
    dest: /etc/nginx/self.crt
  notify: Restart nginx
  tags:
    - configuration

- name: Copy self.key file
  copy:
    src: etc/nginx/self.key
    dest: /etc/nginx/self.key
  notify: Restart nginx
  tags:
    - configuration

- name: Link sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    src: /etc/nginx/sites-available/home
    state: link
  notify: Restart nginx

- import_tasks: certbot.yml
